1 of 3
Georgy-hook/iOS-FakeNFTProject pull request #6
Opened 2023-11-09 21:13 UTC by Crowru

MVP, верстка кодом 
ссылка на доску: https://trello.com/b/wLV6GslG/fakenft
приглашение на доску: https://trello.com/b/wLV6GslG/fakenft (Если нужно)
В трелло мои задачи с обложкой зеленого цвета и помечен я как исполнитель.

2023-11-11 12:55 UTC, protos17 requested changes

2023-11-11 12:55 UTC, protos17 commented on FakeNFT/Scenes /Collection/CollectionCell/CollectionCell.swift
> +            star.image = UIImage(named: "Catalog.starImage")?.withTintColor(color, renderingMode: .alwaysOriginal)
Здесь рекомендовал бы присваивать те картинки, которые сохранил до этого с правильными цветами:

      star.image = position < state ? UIImage(named: "starDoneIcon") : UIImage(named: "defaultStarIcon")

2023-11-11 12:55 UTC, protos17 commented on FakeNFT/Scenes /Catalog/CatalogCell/CatalogCell.swift
> +            previewText.topAnchor.constraint(equalTo: previewImage.bottomAnchor, constant: 4),
Константы для констрейнтов рекомендую выносить в extension класса:

       extension CatalogCell { 
            private enum Constants { 
               static let defaultOffset: CGFloat = 4 
                ... 
           }
          }

2023-11-11 12:55 UTC, protos17 commented on FakeNFT/Scenes /Catalog/CatalogPresenter.swift
> +    private var collections: [CollectionModel] = []
Публичные свойства принято писать раньше приватных

2023-11-11 12:55 UTC, protos17 commented on FakeNFT/Scenes /Catalog/CatalogPresenter.swift
> +        DispatchQueue.global().async {
Сильная ссылка, рекомендую добавить weak self

2023-11-11 12:55 UTC, protos17 commented on FakeNFT/Scenes /Catalog/CatalogPresenter.swift
> +            self.networkClient.send(request: GetCollectionsRequest(), type: [CollectionModel].self) { result in
В этом месте можно не указывать weak self, если выше будет уже указано

2023-11-11 12:55 UTC, protos17 commented on FakeNFT/Scenes /Catalog/CatalogViewController.swift
> +        #warning("Доделать сортировку")
Если что-то нужно доделать, то рекомендую указывать как:

       // TODO: - Доделать сортировку
       
Если подключить swiftlint, то он его тоже будет указывать как warning

2023-11-11 12:55 UTC, protos17 commented on FakeNFT/Scenes /Catalog/epic_catalog_plan.md
Необходимо разделить на 3 части с явным укаазанием, какие задачи в какой части будет выполнены

2023-11-11 12:55 UTC, protos17 commented on FakeNFT/Scenes /Collection/CollectionCell/CollectionCell.swift
> +    }()
Можно немного упростить:

      private let starsImage: [UIImageView] = {
        (1...5).map { _ in
            UIImageView()
        }
    }()

2023-11-11 12:55 UTC, protos17 commented on FakeNFT/Scenes /Collection/CollectionCell/CollectionCell.swift
> +    func cardButtonTap() {
Рекомендую их указывать как private

2023-11-11 12:55 UTC, protos17 commented on FakeNFT/Scenes /Collection/CollectionViewController.swift
> +    }
Рекомендую указывать в extension класса

2023-11-11 12:55 UTC, protos17 commented on FakeNFT/Scenes /Collection/CollectionViewController.swift
> +        let url = URL(string: urlString!)
Рекомендую не использовать принудительное извлечение опционалов, лучше добавить проверку

2023-11-11 12:55 UTC, protos17 commented on FakeNFT/Scenes /Collection/CollectionViewController.swift
> +        return 21
При возвращении значения одной строкой можно не писать return

2023-11-11 12:55 UTC, protos17 commented on FakeNFT/Scenes /TabBarController/TabBarController.swift
> +        //let catalogPresenter = CatalogPresenter(networkClient: DefaultNetworkClient())
Лишний закомментированный код рекомендую удалять

2023-11-11 13:30 UTC, Crowru commented on FakeNFT/Scenes /Collection/CollectionCell/CollectionCell.swift
> +            star.image = UIImage(named: "Catalog.starImage")?.withTintColor(color, renderingMode: .alwaysOriginal)
Поправил

2023-11-11 13:34 UTC, Crowru commented on FakeNFT/Scenes /Catalog/CatalogCell/CatalogCell.swift
> +            previewText.topAnchor.constraint(equalTo: previewImage.bottomAnchor, constant: 4),
исправил

2023-11-11 13:42 UTC, Crowru commented on FakeNFT/Scenes /Catalog/CatalogPresenter.swift
> +    private var collections: [CollectionModel] = []
Я читал что приватные константы всё равно пишутся раньше обычных var

2023-11-11 13:43 UTC, Crowru commented on FakeNFT/Scenes /Catalog/CatalogPresenter.swift
> +        DispatchQueue.global().async {
добавил

2023-11-11 14:34 UTC, Crowru commented on FakeNFT/Scenes /Catalog/epic_catalog_plan.md
Что вы имеете ввиду под разбитием на три части? Вроде нам декомпозицию подтверждал наставник и не было условия что нужно делить ровно на три части. Насколько я понял мы условно делили на три части. В целом я переделаю если нужно но не до конца понимаю что мне сделать конкретно

2023-11-11 14:50 UTC, Crowru commented on FakeNFT/Scenes /Collection/CollectionViewController.swift
> +        let url = URL(string: urlString!)
хорошо, тут для теста делал просто )

2023-11-11 14:51 UTC, Crowru commented on FakeNFT/Scenes /Collection/CollectionCell/CollectionCell.swift
> +    }()
О, красиво )

2023-11-11 14:52 UTC, Crowru commented on FakeNFT/Scenes /TabBarController/TabBarController.swift
> +        //let catalogPresenter = CatalogPresenter(networkClient: DefaultNetworkClient())
удалил уже )

2023-11-11 15:01 UTC, protos17 commented on FakeNFT/Scenes /Catalog/CatalogPresenter.swift
> +    private var collections: [CollectionModel] = []
Рекомендую придерживаться гайдлайнов:
https://github.com/RedMadRobot/RMR-swift-style-guide#code-organization

2023-11-11 15:02 UTC, protos17 commented on FakeNFT/Scenes /Catalog/epic_catalog_plan.md
Ну в самом же задании это прописано в требованиях:
https://admin.praktikum.yandex-team.ru/office/revisor-review/1042545/8d968deae5f3415b868c601c12fdcc4a
![Uploading Снимок экрана 2023-11-11 в 18.00.55.png…]()

2023-11-11 16:45 UTC, Crowru commented on FakeNFT/Scenes /Catalog/epic_catalog_plan.md
То есть мне нужно разделить файлик декомпозиции примерно на три равные части и указать что я из этого сделал? 
Я чуть больше сделал тасков чем 1/3, как мне поступить, добавить сделанных ровно на одну треть а остальное пометить как сделанное но уже например для 2/3 или 3/3.
И получается 1/3 я пройду если исправлю файлик декомпозиции ?

2023-11-11 17:45 UTC, protos17 commented on FakeNFT/Scenes /Catalog/epic_catalog_plan.md
Да, раздели на три, хоть и сделал больше, укажи сделанные только треть. Во второй трети тебе нужно будет меньше сделать

2023-11-11 18:08 UTC, Crowru commented on FakeNFT/Scenes /Catalog/epic_catalog_plan.md
# Каталог

**1 of 3:**
Экран каталога:
Верстка:
- Navigation Bar и кнопка сортировки `1-2 часа` ✅ real: 2,5 часа 
- Table View `2-3 часа` ✅ real: 1 час 
- Ячейки Table View: картинка, название, количество NFT `2 часа` ✅ real: 3 часа
- Алерт сортировки `1 час` ✅ real: 30 минут

Работа с получением данных:
- разбор сетевого слоя `4-6 часов` ✅ real: 5 часов
- написание функций для получения в контроллере `3-4 часа` ✅ real: 4 часа
 
Логика:
- Заполнение таблицы данными `2 часа` ✅ real: 1,5 часа
- Навигация `2 часа` ✅ real: 1,5 часа
- Индикатор загрузки с логикой `2-3 часа` ✅ real: 2,5 часа

**2 of 3:**
Экран каталога:
Логика:
- Кнопка сортировки с логикой `1 день`
- Cохранение порядка сортировки `2 часа`
- Состояния ошибок `1-2 дня`

Экран коллекции NFT:
Верстка:
_ ScrollView `3 часа`
- Обложка `1 час` 
- кнопка возврата на предыдущий экран `1 час`
- название `20 минут`
- автор `20 минут` 
- описание `20 минут` 
- колекция `3 часа` 
- ячейки коллекции `3 часа`
- Переход на сайт по ссылке `2 часа`

**3 of 3:**

Экран коллекции NFT:

Работа с получением данных:
- написание функций запроса данных `6 часов`

Логика:
- Индикатор загрузки с логикой `1,5 часа`
- Заполнение элементов данными `1 час`
- Переход на сайт по ссылке `6 часов`
- Логика кнопки лайка `5-7 часов`
- Логика кнопки корзина `5-7 часов`
- Состояния ошибок `1-2 дня`
- Навигация `2 часа`

2023-11-11 18:08 UTC, Crowru commented on FakeNFT/Scenes /Catalog/epic_catalog_plan.md
если вот так сделаю то нормально ?

2023-11-11 18:09 UTC, protos17 commented on FakeNFT/Scenes /Catalog/epic_catalog_plan.md
Да, отлично

2023-11-12 11:02 UTC, protos17 commented on FakeNFT/Scenes /Catalog/Catalog/CatalogPresenter.swift
> +                        self?.view?.endRefreshing()
Если они дублируются, то рекомендую перенести в общую область видимости

2023-11-12 11:02 UTC, protos17 commented on FakeNFT/Scenes /Catalog/Collection/CollectionPresenter.swift
> +                                    onResponse: {result in
Теперь здесь появилась сильная ссылка :)

2023-11-12 11:02 UTC, protos17 commented on FakeNFT/Scenes /Catalog/Collection/CollectionViewController.swift
>      func didTapUserNameLabel(_ sender: Any) {
Рекомендую указать как private

2023-11-12 11:56 UTC, Crowru commented on FakeNFT/Scenes /Catalog/Catalog/CatalogPresenter.swift
> +                        self?.view?.endRefreshing()
сделал

2023-11-12 11:58 UTC, Crowru commented on FakeNFT/Scenes /Catalog/Collection/CollectionPresenter.swift
> +                                    onResponse: {result in
ой пропустил )

2023-11-12 11:59 UTC, merged